// AIRS Nexus — Generated by AIRS Studio
// DeBacco Nexus LLC · USPTO 19/571,156
process.env.NEXUS_NAME = process.env.NEXUS_NAME || "DeBacco Consulting Practice Hub";
process.env.ENTITY_LABEL = process.env.ENTITY_LABEL || "Client Engagement Record";
process.env.TABLE_NAME = process.env.TABLE_NAME || "client_engagement_record_records";
'use strict';
const express = require('express');
const { Pool } = require('pg');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;
const NEXUS_NAME = process.env.NEXUS_NAME || 'AIRS Nexus';
const TABLE_NAME = process.env.TABLE_NAME || 'records';
const ENTITY_LABEL = process.env.ENTITY_LABEL || 'Record';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

async function initDB() {
  try {
    await pool.query(`CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (id SERIAL PRIMARY KEY, field_1 TEXT, field_2 TEXT, field_3 TEXT, field_4 TEXT, field_5 TEXT, field_6 TEXT, status VARCHAR(50) DEFAULT 'active', notes TEXT, igm_governed BOOLEAN DEFAULT true, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS audit_log (id SERIAL PRIMARY KEY, table_name VARCHAR(100), record_id INTEGER, action_type VARCHAR(20), changed_by VARCHAR(255), field_changed VARCHAR(100), old_value TEXT, new_value TEXT, changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS contact_log (id SERIAL PRIMARY KEY, record_id INTEGER, contact_type VARCHAR(100), notes TEXT, author VARCHAR(255), igm_governed BOOLEAN DEFAULT true, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS documents (id SERIAL PRIMARY KEY, record_id INTEGER, document_type VARCHAR(100), document_source VARCHAR(100), received_via VARCHAR(100), event_date DATE, assigned_to VARCHAR(255), extracted_text TEXT, igm_governed BOOLEAN DEFAULT true, chain_status VARCHAR(50) DEFAULT 'submitted', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS raw_notes (id SERIAL PRIMARY KEY, record_id INTEGER, note_type VARCHAR(50) DEFAULT 'general', content TEXT, author VARCHAR(255), igm_governed BOOLEAN DEFAULT false, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS calendar_events (id SERIAL PRIMARY KEY, record_id INTEGER, event_date DATE, event_type VARCHAR(100), location VARCHAR(255), assigned_to VARCHAR(255), notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
    await pool.query(`ALTER TABLE ${TABLE_NAME} ADD COLUMN IF NOT EXISTS is_demo BOOLEAN DEFAULT false`);
    console.log('[IGM] Database initialized: ' + NEXUS_NAME);
  } catch (err) {
    console.error('[IGM] DB init error:', err.message);
  }
}

async function audit(recordId, action, changedBy) {
  try {
    await pool.query('INSERT INTO audit_log (table_name, record_id, action_type, changed_by) VALUES ($1,$2,$3,$4)', [TABLE_NAME, recordId, action, changedBy || 'system']);
  } catch (err) { console.error('[IGM] Audit error:', err.message); }
}

app.get('/api/records', async (req, res) => {
  try {
    const { search, status } = req.query;
    let q = `SELECT * FROM ${TABLE_NAME}`;
    const params = [];
    const clauses = [];
    if (search) { params.push(`%${search}%`); clauses.push(`(field_1 ILIKE $${params.length} OR field_2 ILIKE $${params.length} OR field_3 ILIKE $${params.length})`); }
    if (status && status !== 'all') { params.push(status); clauses.push(`status = $${params.length}`); }
    if (clauses.length) q += ' WHERE ' + clauses.join(' AND ');
    q += ' ORDER BY created_at DESC';
    const result = await pool.query(q, params);
    res.json({ success: true, records: result.rows, entity: ENTITY_LABEL });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/records/:id', async (req, res) => {
  try {
    const record = await pool.query(`SELECT * FROM ${TABLE_NAME} WHERE id = $1`, [req.params.id]);
    const contacts = await pool.query('SELECT * FROM contact_log WHERE record_id = $1 ORDER BY created_at DESC', [req.params.id]);
    const docs = await pool.query('SELECT * FROM documents WHERE record_id = $1 ORDER BY created_at DESC', [req.params.id]);
    const notes = await pool.query('SELECT * FROM raw_notes WHERE record_id = $1 ORDER BY created_at DESC', [req.params.id]);
    if (!record.rows[0]) return res.status(404).json({ success: false, error: 'Not found' });
    res.json({ success: true, record: record.rows[0], contacts: contacts.rows, documents: docs.rows, notes: notes.rows });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.post('/api/records', async (req, res) => {
  try {
    const { field_1, field_2, field_3, field_4, field_5, field_6, status, notes, created_by } = req.body;
    const result = await pool.query(`INSERT INTO ${TABLE_NAME} (field_1,field_2,field_3,field_4,field_5,field_6,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`, [field_1, field_2, field_3, field_4, field_5, field_6, status || 'active', notes]);
    await audit(result.rows[0].id, 'INSERT', created_by);
    res.status(201).json({ success: true, record: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.put('/api/records/:id', async (req, res) => {
  try {
    const { field_1, field_2, field_3, field_4, field_5, field_6, status, notes, updated_by } = req.body;
    const result = await pool.query(`UPDATE ${TABLE_NAME} SET field_1=$1,field_2=$2,field_3=$3,field_4=$4,field_5=$5,field_6=$6,status=$7,notes=$8,updated_at=CURRENT_TIMESTAMP WHERE id=$9 RETURNING *`, [field_1, field_2, field_3, field_4, field_5, field_6, status, notes, req.params.id]);
    await audit(req.params.id, 'UPDATE', updated_by);
    res.json({ success: true, record: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.delete('/api/records/:id', async (req, res) => {
  try {
    await pool.query(`DELETE FROM ${TABLE_NAME} WHERE id = $1`, [req.params.id]);
    await audit(req.params.id, 'DELETE', req.body?.deleted_by);
    res.json({ success: true });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.post('/api/contacts', async (req, res) => {
  try {
    const { record_id, contact_type, notes, author } = req.body;
    const result = await pool.query('INSERT INTO contact_log (record_id, contact_type, notes, author) VALUES ($1,$2,$3,$4) RETURNING *', [record_id, contact_type, notes, author]);
    res.status(201).json({ success: true, contact: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/notes', async (req, res) => {
  try {
    const { record_id } = req.query;
    const q = record_id ? 'SELECT * FROM raw_notes WHERE record_id = $1 ORDER BY created_at DESC' : 'SELECT * FROM raw_notes ORDER BY created_at DESC LIMIT 100';
    const result = record_id ? await pool.query(q, [record_id]) : await pool.query(q);
    res.json({ success: true, notes: result.rows });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.post('/api/notes', async (req, res) => {
  try {
    const { record_id, note_type, content, author, igm_governed } = req.body;
    const result = await pool.query('INSERT INTO raw_notes (record_id, note_type, content, author, igm_governed) VALUES ($1,$2,$3,$4,$5) RETURNING *', [record_id || null, note_type || 'general', content, author, igm_governed || false]);
    if (igm_governed) await audit(record_id, 'GOVERNED_NOTE', author);
    res.status(201).json({ success: true, note: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/documents', async (req, res) => {
  try {
    const { record_id } = req.query;
    const q = record_id ? 'SELECT * FROM documents WHERE record_id = $1 ORDER BY created_at DESC' : 'SELECT * FROM documents ORDER BY created_at DESC LIMIT 100';
    const result = record_id ? await pool.query(q, [record_id]) : await pool.query(q);
    res.json({ success: true, documents: result.rows });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.post('/api/documents', async (req, res) => {
  try {
    const { record_id, document_type, document_source, received_via, event_date, assigned_to, extracted_text } = req.body;
    const result = await pool.query('INSERT INTO documents (record_id, document_type, document_source, received_via, event_date, assigned_to, extracted_text) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [record_id || null, document_type, document_source, received_via, event_date || null, assigned_to, extracted_text]);
    await audit(record_id, 'DOCUMENT_ADDED', assigned_to);
    res.status(201).json({ success: true, document: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/calendar', async (req, res) => {
  try {
    const { date, location, assigned_to } = req.query;
    let q = `SELECT c.*, r.field_1, r.field_2 FROM calendar_events c LEFT JOIN ${TABLE_NAME} r ON c.record_id = r.id`;
    const params = [];
    const clauses = [];
    if (date) { params.push(date); clauses.push(`c.event_date = $${params.length}`); }
    if (location) { params.push(`%${location}%`); clauses.push(`c.location ILIKE $${params.length}`); }
    if (assigned_to) { params.push(`%${assigned_to}%`); clauses.push(`c.assigned_to ILIKE $${params.length}`); }
    if (clauses.length) q += ' WHERE ' + clauses.join(' AND ');
    q += ' ORDER BY c.event_date ASC';
    const result = await pool.query(q, params);
    res.json({ success: true, events: result.rows });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.post('/api/calendar', async (req, res) => {
  try {
    const { record_id, event_date, event_type, location, assigned_to, notes } = req.body;
    const result = await pool.query('INSERT INTO calendar_events (record_id, event_date, event_type, location, assigned_to, notes) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [record_id || null, event_date, event_type, location, assigned_to, notes]);
    res.status(201).json({ success: true, event: result.rows[0] });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/datalog', async (req, res) => {
  try {
    const { search } = req.query;
    let q = `SELECT r.*, COUNT(c.id) as contact_count, COUNT(d.id) as doc_count FROM ${TABLE_NAME} r LEFT JOIN contact_log c ON c.record_id = r.id LEFT JOIN documents d ON d.record_id = r.id`;
    const params = [];
    if (search) { params.push(`%${search}%`); q += ` WHERE (r.field_1 ILIKE $1 OR r.field_2 ILIKE $1)`; }
    q += ` GROUP BY r.id ORDER BY r.updated_at DESC`;
    const result = await pool.query(q, params);
    res.json({ success: true, records: result.rows, entity: ENTITY_LABEL, nexus: NEXUS_NAME });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/stats', async (req, res) => {
  try {
    const total = await pool.query(`SELECT COUNT(*) FROM ${TABLE_NAME}`);
    const active = await pool.query(`SELECT COUNT(*) FROM ${TABLE_NAME} WHERE status = 'active'`);
    const completed = await pool.query(`SELECT COUNT(*) FROM ${TABLE_NAME} WHERE status = 'completed'`);
    const recent = await pool.query(`SELECT COUNT(*) FROM ${TABLE_NAME} WHERE created_at > NOW() - INTERVAL '30 days'`);
    const auditCount = await pool.query('SELECT COUNT(*) FROM audit_log');
    const timeSeries = await pool.query(`SELECT DATE(created_at) as date, COUNT(*) as count FROM ${TABLE_NAME} WHERE created_at > NOW() - INTERVAL '30 days' GROUP BY DATE(created_at) ORDER BY date ASC`);
    const statusBreakdown = await pool.query(`SELECT status, COUNT(*) as count FROM ${TABLE_NAME} GROUP BY status`);
    const fieldDist = await pool.query(`SELECT field_3, COUNT(*) as count FROM ${TABLE_NAME} WHERE field_3 IS NOT NULL AND field_3 != '' GROUP BY field_3 ORDER BY count DESC LIMIT 10`);
    const govActivity = await pool.query(`SELECT DATE(changed_at) as date, COUNT(*) as count FROM audit_log WHERE changed_at > NOW() - INTERVAL '30 days' GROUP BY DATE(changed_at) ORDER BY date ASC`);
    res.json({ success: true, stats: { total: parseInt(total.rows[0].count), active: parseInt(active.rows[0].count), completed: parseInt(completed.rows[0].count), recent_30_days: parseInt(recent.rows[0].count), audit_entries: parseInt(auditCount.rows[0].count), nexus_name: NEXUS_NAME, entity_label: ENTITY_LABEL, igm_governed: true }, charts: { time_series: timeSeries.rows, status_breakdown: statusBreakdown.rows, field_distribution: fieldDist.rows, governance_activity: govActivity.rows } });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('/api/health', (req, res) => {
  res.json({ success: true, nexus: NEXUS_NAME, entity: ENTITY_LABEL, igm: 'GOVERNED', timestamp: new Date().toISOString() });
});

// --- AIRS Demo Sample Data (synthetic, no real PII) ---
const DEMO_CAST = ['Alex Rivera','Jordan Lee','Sam Okafor','Taylor Nguyen','Morgan Castillo','Casey Brightwater','Riley Cohen','Devon Park'];
function demoValue(label, i) {
  const L = (label || '').toUpperCase();
  if (L.includes('NAME') && !L.includes('USERNAME')) return DEMO_CAST[i];
  if (L.includes('ID') || L.includes('#') || L.includes('CASE') || L.includes('NUMBER')) return 'DEMO-' + (1001 + i);
  if (L.includes('DATE')) { const d = new Date(); d.setDate(d.getDate() - (i * 11 + 3)); return d.toISOString().slice(0, 10); }
  if (L.includes('PHONE')) return '(555) 010' + i;
  if (L.includes('EMAIL')) return 'demo' + (i + 1) + '@example.com';
  if (L.includes('LOCATION') || L.includes('SITE') || L.includes('COURT') || L.includes('FACILITY')) return 'Demo Site ' + String.fromCharCode(65 + (i % 4));
  if (L.includes('TEAM') || L.includes('ASSIGNED') || L.includes('WORKER') || L.includes('STAFF')) return 'Demo Staff ' + String.fromCharCode(65 + (i % 3));
  return 'Sample ' + (label || 'Entry') + ' ' + (i + 1);
}
app.post('/api/demo/seed', async (req, res) => {
  try {
    await initDB(); // self-heal: never depend on boot order against fresh Postgres
    const existing = await pool.query(`SELECT COUNT(*) FROM ${TABLE_NAME} WHERE is_demo = true`);
    if (parseInt(existing.rows[0].count) > 0) {
      return res.json({ success: true, seeded: 0, existing: parseInt(existing.rows[0].count), message: 'Sample data already loaded' });
    }
    const rawFields = (req.body && req.body.fields) || [];
    const fields = rawFields.map(f => (typeof f === "string" ? f.substring(0, 30) : f));
    const statuses = ['active','active','active','active','active','completed','pending','active'];
    let seeded = 0;
    for (let i = 0; i < 8; i++) {
      const vals = [0,1,2,3,4,5].map(f => {
        let v = demoValue(fields[f], i);
        if (typeof v === "string") {
            // Strips out JSON breaking characters but preserves readable math notation cleanly
            return v.replace(/[\\\"]/g, "").replace(/[\x00-\x1F\x7F-\x9F]/g, "").replace(/\//g, " per ").substring(0, 40);
        }
        return v;
      }); // narrativeMathSanitizer
      const r = await pool.query(
        `INSERT INTO ${TABLE_NAME} (field_1,field_2,field_3,field_4,field_5,field_6,status,notes,is_demo) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,true) RETURNING id`,
        vals.concat([statuses[i], '[DEMO] Synthetic record for demonstration only - no real PII'])
      );
      const rid = r.rows[0].id;
      await pool.query(`INSERT INTO contact_log (record_id, contact_type, notes, author) VALUES ($1,$2,$3,$4)`,
        [rid, 'Demo Contact', '[DEMO] Synthetic contact entry - governed and logged', 'AIRS Demo']);
      const ev = new Date(); ev.setDate(ev.getDate() + (i * 4 + 2));
      await pool.query(`INSERT INTO calendar_events (record_id, event_date, event_type, location, assigned_to, notes) VALUES ($1,$2,$3,$4,$5,$6)`,
        [rid, ev.toISOString().slice(0, 10), 'Demo Review', 'Demo Site A', 'Demo Staff A', '[DEMO]']);
      seeded++;
    }
    console.log('[IGM] Demo seed: ' + seeded + ' synthetic records loaded');
    res.json({ success: true, seeded });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});
app.delete('/api/demo/clear', async (req, res) => {
  try {
    const ids = await pool.query(`SELECT id FROM ${TABLE_NAME} WHERE is_demo = true`);
    const list = ids.rows.map(r => r.id);
    if (list.length) {
      await pool.query(`DELETE FROM contact_log WHERE record_id = ANY($1)`, [list]);
      await pool.query(`DELETE FROM calendar_events WHERE record_id = ANY($1)`, [list]);
      await pool.query(`DELETE FROM documents WHERE record_id = ANY($1)`, [list]);
      await pool.query(`DELETE FROM raw_notes WHERE record_id = ANY($1)`, [list]);
      await pool.query(`DELETE FROM ${TABLE_NAME} WHERE is_demo = true`);
    }
    console.log('[IGM] Demo clear: ' + list.length + ' synthetic records removed');
    res.json({ success: true, cleared: list.length });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

// --- GDI: Governed Data Intelligence (Tier 2) - deterministic cross-record inference, zero tokens ---
app.get('/api/viz/aggregate', async (req, res) => {
  try {
    const fld = String(req.query.field || 'status');
    const allowed = ['field_1','field_2','field_3','field_4','field_5','field_6','status'];
    if (!allowed.includes(fld)) return res.json({ success: false, error: 'invalid field' });
    const rows = (await pool.query(`SELECT COALESCE(NULLIF(TRIM(${fld}),''),'(blank)') AS label, COUNT(*)::int AS n FROM ${TABLE_NAME} GROUP BY 1 ORDER BY n DESC LIMIT 12`)).rows;
    const total = (await pool.query(`SELECT COUNT(*)::int AS t FROM ${TABLE_NAME}`)).rows[0].t;
    res.json({ success: true, field: fld, total: total, buckets: rows, governed: true, generated_at: new Date().toISOString() });
  } catch (e) { res.json({ success: false, error: e.message }); }
});

app.post('/api/gdi/analyze', async (req, res) => {
  const t0 = Date.now();
  try {
    const findings = [];
    const recs = (await pool.query(`SELECT id, field_1, field_2, field_3, field_4, field_5, field_6, status, created_at, is_demo FROM ${TABLE_NAME}`)).rows;
    const contacts = (await pool.query('SELECT record_id, MAX(created_at) AS last_contact FROM contact_log GROUP BY record_id')).rows;
    const events = (await pool.query(`SELECT record_id, event_date, event_type FROM calendar_events WHERE event_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '7 days'`)).rows;
    const lastContact = {}; contacts.forEach(c => lastContact[c.record_id] = new Date(c.last_contact));
    const now = new Date(); const DAY = 86400000;

    const active = recs.filter(r => r.status === 'active');
    const stale = active.filter(r => !lastContact[r.id] || (now - lastContact[r.id]) > 30 * DAY);
    if (stale.length) findings.push({ rule: 'GDI-R1', severity: 'HIGH', title: 'Active records without recent contact', description: stale.length + ' of ' + active.length + ' active records have no logged contact in the last 30 days.', evidence: stale.map(r => r.id) });
    else if (active.length) findings.push({ rule: 'GDI-R1', severity: 'PASS', title: 'Contact recency verified', description: 'All ' + active.length + ' active records have a logged contact within 30 days.', evidence: active.map(r => r.id) });

    const pending = recs.filter(r => r.status === 'pending');
    const agedPending = pending.filter(r => (now - new Date(r.created_at)) > 14 * DAY);
    if (agedPending.length) findings.push({ rule: 'GDI-R2', severity: 'HIGH', title: 'Pending records aging past 14 days', description: agedPending.length + ' pending record(s) have waited more than 14 days for review.', evidence: agedPending.map(r => r.id) });
    else if (pending.length) findings.push({ rule: 'GDI-R2', severity: 'INFO', title: 'Pending records in queue', description: pending.length + ' record(s) currently pending review, all within the 14-day window.', evidence: pending.map(r => r.id) });

    if (events.length) {
      const unprepared = events.filter(e => !lastContact[e.record_id]);
      if (unprepared.length) findings.push({ rule: 'GDI-R3', severity: 'HIGH', title: 'Upcoming events without contact', description: unprepared.length + ' event(s) in the next 7 days belong to records with no contact logged.', evidence: unprepared.map(e => e.record_id) });
      else findings.push({ rule: 'GDI-R3', severity: 'INFO', title: 'Events in the next 7 days', description: events.length + ' upcoming event(s); every linked record has contact history.', evidence: [...new Set(events.map(e => e.record_id))] });
    }

    if (recs.length) {
      let filled = 0; const weak = [];
      for (let f = 1; f <= 6; f++) {
        const have = recs.filter(r => r['field_' + f] && String(r['field_' + f]).trim()).length;
        const pct = Math.round(100 * have / recs.length);
        filled += pct;
        if (pct < 60) weak.push('field_' + f + ' (' + pct + '%)');
      }
      const overall = Math.round(filled / 6);
      if (weak.length) findings.push({ rule: 'GDI-R4', severity: 'MODERATE', title: 'Governed fields under-populated', description: 'Fields below 60% completeness: ' + weak.join(', ') + '. Overall completeness ' + overall + '%.', evidence: [] });
      else findings.push({ rule: 'GDI-R4', severity: 'PASS', title: 'Field completeness ' + overall + '%', description: 'All six governed fields exceed the 60% completeness floor across ' + recs.length + ' records.', evidence: [] });
    }

    const dist = {}; recs.forEach(r => dist[r.status] = (dist[r.status] || 0) + 1);
    findings.push({ rule: 'GDI-R5', severity: 'INFO', title: 'Status distribution', description: Object.entries(dist).map(([k, v]) => v + ' ' + k).join(' / ') + ' across ' + recs.length + ' total records.', evidence: [] });

    const receipts = { records_scanned: recs.length, rules_executed: 5, tokens_in: 0, tokens_out: 0, duration_ms: Date.now() - t0, ran_at: new Date().toISOString() };
    try { await pool.query('INSERT INTO audit_log (table_name, action_type, changed_by, new_value) VALUES ($1,$2,$3,$4)', ['gdi_runs', 'GDI_RUN', req.body && req.body.run_by || 'operator', JSON.stringify({ findings: findings.length, ...receipts })]); } catch (e) {}
    console.log('[IGM] GDI run: ' + findings.length + ' findings, ' + recs.length + ' records, 0 tokens, ' + receipts.duration_ms + 'ms');
    res.json({ success: true, tier: 'GDI - Governed Data Intelligence', findings, receipts });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

// === NEXUS LIVE — governed live inference (IGM USPTO 19/571,156) ===
app.post('/api/nexus/live', async (req, res) => {
  const t0 = Date.now();
  try {
    const question = ((req.body && req.body.question) || '').trim().substring(0, 500);
    if (!question) return res.status(400).json({ success: false, error: 'Question required' });
    if (!process.env.ANTHROPIC_API_KEY) return res.status(503).json({ success: false, error: 'Live inference not enabled - set ANTHROPIC_API_KEY in Railway variables' });
    const labels = (Array.isArray(req.body && req.body.fields) ? req.body.fields : []).map(x => String(x || '').substring(0, 40)).filter(Boolean);
    const recs = (await pool.query(`SELECT id, field_1, field_2, field_3, field_4, field_5, field_6, status, notes, created_at FROM ${TABLE_NAME} ORDER BY created_at DESC LIMIT 50`)).rows;
    const context = recs.map(r => '#' + r.id + '|' + [r.field_1,r.field_2,r.field_3,r.field_4,r.field_5,r.field_6].map(v=>v||'').join('|') + '|' + (r.status||'') + '|' + ((r.notes||'').substring(0,80))).join('\n');
    const resp = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': process.env.ANTHROPIC_API_KEY, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({
        model: 'claude-haiku-4-5',
        max_tokens: 300,
        system: 'You are Nexus Live, the IGM-governed live inference layer (300-token budget). Answer ONLY from the governed records provided. If the records cannot answer, name exactly what is missing. Be concise.',
        messages: [{ role: 'user', content: 'Governed records (id|' + (labels.length ? labels.join('|') : 'f1-f6') + '|status|notes):\n' + context + '\n\nQuestion: ' + question }]
      })
    });
    const d = await resp.json();
    if (!resp.ok) return res.status(502).json({ success: false, error: (d.error && d.error.message) || 'Inference failed' });
    const answer = (d.content || []).filter(c => c.type === 'text').map(c => c.text).join('\n');
    const ti = (d.usage && d.usage.input_tokens) || 0, to = (d.usage && d.usage.output_tokens) || 0;
    const rq = +((recs.length / Math.max(1, ti + to)) + ((Date.now() - t0) / 1000)).toFixed(3);
    const receipts = { tier: 'Nexus Live', records_scanned: recs.length, tokens_in: ti, tokens_out: to, rq, model: 'claude-haiku-4-5', duration_ms: Date.now() - t0, ran_at: new Date().toISOString() };
    try { await pool.query('INSERT INTO audit_log (table_name, action_type, changed_by, new_value) VALUES ($1,$2,$3,$4)', ['nexus_live', 'LIVE_INFERENCE', (req.body && req.body.run_by) || 'operator', JSON.stringify({ question, ...receipts })]); } catch (e) {}
    console.log('[IGM] Nexus Live: ' + recs.length + ' records, ' + (ti + to) + ' tokens, ' + receipts.duration_ms + 'ms');
    res.json({ success: true, answer, receipts });
  } catch (err) { res.status(500).json({ success: false, error: err.message }); }
});

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

initDB().then(() => {
  app.listen(PORT, () => { console.log('[IGM] ' + NEXUS_NAME + ' live on port ' + PORT); });
});
